# Kaggle Competition
June 09, 2026

---

This notebook will contain background, set up exploration data analysis, and testing models to predicts Dissolved Inorganic Carbon (DIC) (µmol/kg) for seawater samples collected off the California coast. The data come from the California Cooperative Oceanic Fisheries Investigations (CalCOFI) program, one of the longest-running oceanographic time series in the world, collecting data across the California Current System since 1949.

## Background - Pat

# Libraries used in this notebook

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_squared_error, r2_score
from ipywidgets import interact, FloatLogSlider
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, roc_auc_score,
                              RocCurveDisplay, ConfusionMatrixDisplay)
import kagglehub # Kaggle Website

# Setting Seed
np.random.seed(42) # Best Number

# Add Data

In [26]:
# Download latest version
test = pd.read_csv('data/test.csv')
train = pd.read_csv('data/train.csv')

## Exploration Data Analysis (EDA)

In [42]:
print(f'Total Rows in Test:', test.shape[0]) # Rows
print(f'Total Columns in Test:', test.shape[1]) # Columns
print(f'NA Values:', test.isna().sum()) # Check NA values

Total Rows in Test: 848
Total Columns in Test: 5
NA Values: id                0
CTDTEMP_ITS90     0
Salinity_PSS78    0
Depth             0
TA                0
dtype: int64

In [43]:
print(f'Total Rows in Train:', train.shape[0]) # Rows
print(f'Total Columns in Train:', train.shape[1]) # Columns
print(f'NA Values:', train.isna().sum()) # Check NA values

Total Rows in Train: 3389
Total Columns in Train: 6
NA Values: id                0
CTDTEMP_ITS90     0
Salinity_PSS78    0
Depth             0
TA                0
DIC               0
dtype: int64

In [28]:
# View top 5 rows
test.head()

   id  CTDTEMP_ITS90  Salinity_PSS78  Depth      TA
0   6          15.23         33.3950   10.0  2241.0
1   8          11.23         33.2320   10.0  2241.0
2  12          19.33         33.4550   10.0  2241.0
3  14          20.96         33.4670   10.0  2241.0
4  17          11.23         33.6095   10.0  2241.0

In [29]:
# View top 5 rows
train.head()

   id  CTDTEMP_ITS90  Salinity_PSS78  Depth      TA     DIC
0   0          15.36         33.6095   10.0  2241.0  1989.4
1   1          11.23         33.6095   10.0  2241.0  1989.8
2   2          11.23         33.6095   10.0  2241.0  1989.3
3   3          11.23         33.6095   10.0  2241.0  1988.6
4   4          15.06         33.2820   10.0  2241.0  1991.5

In [36]:
test.dtypes

id                  int64
CTDTEMP_ITS90     float64
Salinity_PSS78    float64
Depth             float64
TA                float64
dtype: object

In [31]:
train.dtypes

id                  int64
CTDTEMP_ITS90     float64
Salinity_PSS78    float64
Depth             float64
TA                float64
DIC               float64
dtype: object

In [ ]:
# Extract feature names 
feature_names = ['CTDTEMP_ITS90', 'Salinity_PSS78', 'Depth', 'TA']

#
X = train.drop(columns=["DIC"]) 
y = train["target"]
X_test = test.drop(columns=["target"], errors="ignore") 

# split training data for validation/tuning 
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42) 
 
# scale (fit on train only) 
scaler = StandardScaler().fit(X_train) 

X_train_s = scaler.transform(X_train) 

X_val_s = scaler.transform(X_val) 

X_test_s = scaler.transform(X_test)

KeyError: "['target'] not found in axis"